config/routes.rb
Rails.application.routes.draw do
  resources :speakers

  root "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :courses
  resources :events
end

app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :speaker
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_attached_file :banner, :styles => { :medium => "1000x400>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :banner, :content_type => /\Aimage\/.*\Z/
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  belongs_to :user
  has_many :courses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  before_save :create_role

  belongs_to :role
  devise :omniauthable, :omniauth_providers => [:facebook]

  def is?(role)
  	self.role.name.to_sym === role
  end

  def self.find_or_create_by_omniauth(auth)
    if user = User.find_by_email(auth.info.email)
      if auth.info.image.present?
        user.update_attribute(:image, auth.info.image)
      end
    else
      user = User.new
	    user.email = auth.info.email
	    user.password = user.password_confirmation = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
	    user.image = auth.info.image # assuming the user model has an image
	  end
    user
	end

  # Used for devise if the provider doesn't provide some information
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
        user.name = data["name"] if user.name.blank?
        user.image = data["image"] if user.image.blank?
      end
    end
  end	
private
  def create_role
    if !self.role
      self.update_attribute(:role_id, Role.find_by_name('user').id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_event
  before_action :configure_permited_params, if: :devise_controller?

protected
	def set_event 
		@event_main = Event.first
	end

	def configure_permited_params
		news_attrs = [:name, :role_id]
		devise_parameter_sanitizer.for(:sign_up) << :name
		devise_parameter_sanitizer.for(:account_update) << news_attrs 
	end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @courses = Course.all
    respond_with(@courses)
  end

  def show
    respond_with(@course)
  end

  def new
    @course = Course.new
    respond_with(@course)
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    @course.save
    respond_with(@course)
  end

  def update
    @course.update(course_params)
    respond_with(@course)
  end

  def destroy
    @course.destroy
    respond_with(@course)
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :description, :duration, :speaker_id, :date)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	
	def edit
	end

	def update
		if @event_main.update(event_params)
			redirect_to	root_path, notice: 'Banner alterado com sucesso.'
		else
			render 'update'
		end
	end

private
	def event_params
		params.require(:event).permit(:event_id, :name, :banner, :when, :where, :theme, :description)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@speakers = Speaker.all
  	@courses = Course.all

  	render layout: 'home_layout.html.erb'
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  before_action :set_speaker, only: [:show, :edit, :update, :destroy]
  before_action :is_admin, only: [:new, :create, :edit, :update, :destroy]

  respond_to :html

  def index
    @speakers = Speaker.all
    respond_with(@speakers)
  end

  def show
    respond_with(@speaker)
  end

  def new
    @speaker = Speaker.new
    respond_with(@speaker)
  end

  def edit
  end

  def create
    @speaker = Speaker.new(speaker_params)
    @speaker.save
    respond_with(@speaker)
  end

  def update
    @speaker.update(speaker_params)
    respond_with(@speaker)
  end

  def destroy
    @speaker.destroy
    respond_with(@speaker)
  end

  private
    def set_speaker
      @speaker = Speaker.find(params[:id])
    end

    def speaker_params
      params.require(:speaker).permit(:bio, :description, :user_id)
    end

    def is_admin
      if user_signed_in?
        if !current_user.is?(:admin)
          redirect_to root_path
        end
      else
        redirect_to root_path
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
		@user = User.find_or_create_by_omniauth(request.env["omniauth.auth"])
		if @user.save
			sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
			set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/views/courses/_form.html.erb
<%= simple_form_for @course do |f| %>

    <% if @course.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <%= f.input :name, label: 'Nome' %>
  <%= f.input :description, label: 'Descrição' %>
  <%= f.input :duration, label: 'Duração', placeholder: '1 hora' %>
  <%= f.input :date, label: 'Date', placeholder: '17 de fevereiro' %>
  <%= f.association :speaker, label: 'Palestrante' %>


  <%= f.submit "Salvar", :class => 'btn btn-primary' %>
  <%= link_to "Cancelar",
            courses_path, :class => 'btn btn-default' %>

<% end %>

app/views/courses/edit.html.erb
<div class="page-header">
  <h1>Editar curso/palestra</h1>
</div>
<%= render :partial => 'form' %>

app/views/courses/index.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:duration) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.id, course_path(course) %></td>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= course.duration %></td>
        <td><%=l course.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_course_path(course), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      course_path(course),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_course_path,
            :class => 'btn btn-primary' %>

app/views/courses/new.html.erb
<div class="page-header">
  <h1>Criar curso/palestra</h1>
</div>
<%= render :partial => 'form' %>

app/views/courses/show.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @course.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @course.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:duration) %>:</strong></dt>
  <dd><%= @course.duration %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              courses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_course_path(@course), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              course_path(@course),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/events/_form.html.erb
<%= simple_form_for @event_main, html: { multipart: true } do |f| %>
	<% if @event_main.errors.any? %>
		<div class="errors">
			<%= @event_main.errors.count %> erro(s)
		</div>
		<ul>
			<% @event_main.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
	
	<%= f.file_field :banner, label: "Banner" %>
	<%= f.input :name, label: "Nome" %>
	<%= f.input :theme, label: "Tema", placeholder: "Caso não, deixe vazio" %>
	<%= f.input :when, label: "Quando", placeholder: "17 à 15 de janeiro" %>
	<%= f.input :where, label: "Onde", placeholder: "Universidade Qualquer, Av. José Maria, 182, Água Linda" %>
	<%= f.input :description, label: "Descrição" %>
	<%= f.button :submit, "Salvar" %>
<% end %>

app/views/events/edit.html.erb
<h1 class="page-header">Definir evento</h1>
<%= render 'form' %>

app/views/home/index.html.erb
<!-- <div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div> -->

<div class="header-mask" style="background-image: url(<%= @event_main.banner.url %>)">
	<div class="jumbotron header-banner fullscreen">
			<div class="container"> 
				<div class="event-title">
					<h1><%= @event_main.name %></h1>
					<%= content_tag :p, @event_main.theme if @event_main.theme %>
				</div>
				<div class="event-convertion">
					<%= 
					link_to "Participe!", user_omniauth_authorize_path(:facebook), class: 'btn btn-default btn-lg' 
					%>
				</div>
		</div>
	</div>
</div>

<div class="event-details-holder">
	<div class="container">
		<div class="event-details row">
			<div class="event-when col-md-3">
				<div class="icon-holder">
					<i class="fa fa-calendar-o"></i>
				</div>
				<div class="sayings">
					<h3>Quando</h3>
					<p><%= @event_main.when %></p>
				</div>
			</div> 
			<div class="event-where col-md-3">
				<div class="icon-holder">	
					<i class="fa fa-map-marker"></i>
				</div>
				<div class="sayings">
					<h3>Onde</h3>
					<p><%= @event_main.where %></p>
				</div>
			</div>
			<div class="event-speakers col-md-3">
				<div class="icon-holder">	
					<i class="fa fa-users"></i>
				</div>
				<div class="sayings">
					<h3><%= @speakers.size %></h3>
					<p>Palestrantes</p>
				</div>			
			</div>				

			<div class="event-courses col-md-3">
				<div class="icon-holder">	
					<i class="fa fa-users"></i>
				</div>
				<div class="sayings">
					<h3><%= @courses.size %></h3>
					<p>Palestras/Mini-cursos</p>
				</div>			
			</div>	
		</div>
	</div>	
</div>

<% if @event_main.description %>
<div class="event-description-full">
	<div class="jumbotron">
		<h1><%= @event_main.name %></h1>
		<div class="event-desc-text">
			<p><%= @event_main.description %></p>
			<p><%= link_to "Quero participar!", user_omniauth_authorize_path(:facebook), class: 'btn btn-primary btn-lg' %></p>			
		</div>
	</div>		
<% end%>

<div class="speakers-container">
	<div class="container">
		<h2 class="page-header">Palestrantes</h2>

		<% @speakers.each_slice(3) do |group| %>
			<div class="row speakers-row">
			<% group.each do |speaker| %>
				<div class="col-md-4 speakers">
				<!-- <div class="speaker-pic" style="background-image:url(<%= speaker.user.image %>?type=large)"></div> -->
					<%= 
					image_tag speaker.user.image.try(:+, '?height=200&type=normal&width=200'), class: 'img-circle', width: '200' 
					%>
					<h3 class="speaker-title"><%= speaker.user.name %></h3>
					<p class="speaker-bio"><%= speaker.bio %></p>
				</div>
			<% end %>
			</div>
		<% end %>
	</div>	
</div>

<div class="courses-container">
</div>

app/views/layouts/_footer.html.erb
<footer>&copy; EventPage - 2015 </footer>

app/views/layouts/_header.html.erb
<nav id="menu" class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to (content_tag :i, '', class: 'fa fa-home'), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          
          <% if current_user.is?(:admin) %>
            <li>
              <%= link_to 'Editar evento', edit_event_path(@event_main) %>
            </li>

            <li>
              <%= link_to 'Editar palestrantes', speakers_path %>
            </li>

            <li>
              <%= link_to 'Editar palestras', courses_path %>
            </li>            
          <% end %>      
            
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user[:email] %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to "Sair", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to "Criar conta ou entrar", user_omniauth_authorize_path(:facebook) %>
          </li>   
        <% end %>
      </ul>
</nav>

app/views/layouts/_home_header.html.erb
<nav id="menu" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to @event_main.name, root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          
          <% if current_user.is?(:admin) %>
            <li>
              <%= link_to 'Editar evento', edit_event_path(@event_main) %>
            </li>

            <li>
              <%= link_to 'Editar palestrantes', speakers_path %>
            </li>
          <% end %>      
            
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user[:email] %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to "Sair", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to "Criar conta ou entrar", user_omniauth_authorize_path(:facebook) %>
          </li>   
        <% end %>
      </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventpage</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans|Lato:300,400|Varela+Round|Montserrat:300,400|Raleway:400,200">
</head>
<body>
<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |name, msg| %>
    <div class='alert alert-info alert-dismissible' role="alert">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
       </button>
       <%= msg %>
    </div>
  <% end %>
	<%= yield %>
</div>

<%= render 'layouts/footer' %>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1535127033410005',
      xfbml      : true,
      version    : 'v2.2'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
</body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventpage</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans|Lato:300,400|Varela+Round|Montserrat:300,400|Raleway:400,200|Oswald|Roboto+Condensed">
</head>
<body>
<%= render 'layouts/home_header' %>

<%= yield %>

<%= render 'layouts/footer' %>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1535127033410005',
      xfbml      : true,
      version    : 'v2.2'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<script type="text/javascript">
  'use strict';

$(document).ready(function(){
  var elHeight = $('.header-mask').height();

  $(window).on('scroll', function(e){
    if( window.scrollY >= elHeight){
      $('#menu').removeClass('navbar-bg');
    } else {
      $('#menu').addClass('navbar-bg');
    }
  })
});


</script>
</body>
</html>

app/views/speakers/_form.html.erb
<%= simple_form_for @speaker, html:  { :class => 'form-horizontal' } do |f| %>
  <%= f.association :user, label: 'Usuário' %>
  <%= error_span(@speaker[:user_id]) %>
  <%= f.input :bio %>
  <%= error_span(@speaker[:bio]) %>
  <%= f.input :description, label: "Descrição" %>
  <%= error_span(@speaker[:description]) %>

  <%= f.button :submit, "Salvar", :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                speakers_path, :class => 'btn btn-default' %>
<% end %>

app/views/speakers/edit.html.erb
<div class="page-header">
  <h1>Editar</h1>
</div>
<%= render :partial => 'form' %>

app/views/speakers/index.html.erb
<div class="speakers-container">
  <h2 class="page-header">Palestrantes</h2>

  <% @speakers.each_slice(3) do |group| %>
    <div class="row speakers-row">
    <% group.each do |speaker| %>
      <div class="col-md-4 speakers">
      <!-- <div class="speaker-pic" style="background-image:url(<%= speaker.user.image %>?type=large)"></div> -->
        <%= 
        image_tag speaker.user.image.try(:+, '?height=200&type=normal&width=200'), class: 'img-circle' 
        %>
        <h3 class="speaker-title"><%= speaker.user.name %></h3>
        <p class="speaker-bio"><%= speaker.bio %></p>
        <div class='btn-group'>
          <%= link_to 'Editar',
                      edit_speaker_path(speaker), class: 'btn btn-default' %>
          <%= link_to "Remover",
                      speaker_path(speaker),
                      method: :delete,
                      data: { confirm: 'Tem certeza?' },
                      class: 'btn btn-danger' %>          
        </div>
      </div>
    <% end %>
    </div>
  <% end %>

<p class="col-md-12">
<%= link_to 'Adicionar palestrante',
            new_speaker_path,
            :class => 'btn btn-primary' %>
</p>  
</div>

app/views/speakers/new.html.erb
<%- model_class = Speaker -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Novo %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/speakers/show.html.erb
<%- model_class = Speaker -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:bio) %>:</strong></dt>
  <dd><%= @speaker.bio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @speaker.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @speaker.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              speakers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_speaker_path(@speaker), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              speaker_path(@speaker),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>